# Generated by Django 5.0.3 on 2026-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_profile_data_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recruiter_profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
