# Generated by Django 5.0.3 on 2026-06-06 14:01

import random
import string
from django.db import migrations, models

def populate_access_codes(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        if not event.access_code:
            while True:
                code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
                if not Event.objects.filter(access_code=code).exists():
                    event.access_code = code
                    break
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.RunPython(populate_access_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='access_code',
            field=models.CharField(blank=True, default='', max_length=12, unique=True),
        ),
    ]
